version: "3.8" 

services: 
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - 8080:8080 
    
      
    depends_on:
      - mariadb

  mysqldb: # alias réseau, 
    image: mariadb@sha256:310d29fbb58169dcddb384b0ff138edb081e2773d6e2eceb976b3668089f2f84
    ports:
      - 3306:3306
    volumes: 
      - yelp-mariadb-data:/var/lib/mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testsql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:  # volume persistant
  yelp-mariadb-data: